In [4]:
load('../Sage Code/sidon_cryptosystem.sage')

In [5]:
##minrank minor attack on the sidon cryptosystem. 
##Construct the cryptosystem

q = 7
basefield = GF(q)
k = 5
r = 2
rk = r*k
y, F, F_r, d, c = ConstructSidon2k(q, k)
matrixList, sidonbasis, mult_table, F_r_basis , origbasis = fakePublicKey(y,q,F,F_r)
basefield = GF(q)

##Construct a random basis for F_r 
F_r_basis_new = Matrix(basefield, rk, lambda i,j: basefield.random_element())
while F_r_basis_new.is_invertible() == False: 
     F_r_basis_new = Matrix(basefield, rk, lambda i,j: basefield.random_element())
cob_matrix = F_r_basis_new.inverse()
basiselements = []
for i in range(rk): 
    basiselements += [convertFromLong(F_r_basis_new[i], F, F_r)]
    

NameError: name 'fakePublicKey' is not defined

In [ ]:
vector(basiselements)

In [1]:
def fakePublicKey(y,q, F, F_r): 
    ##Generates the public key (and associated private key) using info from the given sidon space 
    p = F.characteristic()
    k = len(F.modulus().list()) - 1
    print(k)
    r = len(F_r.modulus().list()) - 1

    rk = (len(F_r.modulus().list()) - 1)*k
    basefield = GF(q)
    iterations = 0
    iterations2 = 0
    
    ##Construct bases for the sidon space as well as F_r
    sidonbasis = Matrix(basefield, k, lambda i,j: basefield.random_element()*0)
    while sidonbasis.is_invertible() == False and iterations < 500:
        element = F.random_element()
        sidonbasis = Matrix([list(vector(element^(q^i))) for i in range(k)])
        iterations += 1
   
    
    ##Get the multiplication table from the basis of the sidon space
    print(sidonbasis[0])
    v = [F(list(sidonbasis[i])) for i in range(k)]
    origbasis = sidonbasis
    ##sidonbasis = [j + j^q*y for  j in v]
    sidonbasis = [j + j^q*y for  j in v]
    ##sidonbasis = [j*y*y^-1 for j in v]
    
    mult_table = vector(sidonbasis).column()*vector(sidonbasis).row()

   
    ##extension = [convertToLong(F_r.random_element()) for i in range(k)]
    ##mat = Matrix([convertToLong(i) for i in sidonbasis] + extension)
    ##while mat.is_invertible() == False: 
      ##  extension = [convertToLong(F_r.random_element()) for i in range(k)]
     ##   mat = Matrix([convertToLong(i) for i in sidonbasis] + extension)
   
    ##F_r_basis = mat
    extended_basis = [[j*y^i for j in v] for i in range(r)]
    vec_extended_basis  = []
    for j in extended_basis:
        vec_extended_basis += j
    extended_basis  = Matrix([convertToLong(i) for i in vec_extended_basis])
    assert(extended_basis.is_invertible() == True)
    print(extended_basis.nrows(), extended_basis.ncols())
    F_r_basis = extended_basis
    assert(iterations<500 and iterations2<500)
    cob_matrix = F_r_basis.inverse()
    print(cob_matrix)
    vec_list = [[0 for i in range(k)] for j in range(k)]

    ##Generate the public key M(V,B)
    for i in range(k): 
        for j in range(k):
            element = mult_table[i][j]
            long_representation = convertToLong(element)
            vec_list[i][j] = list(long_representation*cob_matrix) 
    matrixlist = [0 for i in range(rk)]
    
    ##Return the public key 
    for i in range(rk): 
        matrixlist[i] = Matrix(basefield, k, lambda l,j: vec_list[l][j][i])
    return matrixlist, sidonbasis, mult_table, F_r_basis, origbasis

In [ ]:
new_mult_table

In [29]:
c_matrix = [[0 for i in range(rk)] for j in range(rk)]
new_mult_table = [[i*j for i in basiselements] for j in basiselements]
for i in range(rk): 
    for j in range(rk): 
        element = convertToLong(new_mult_table[i][j])
        c_matrix[i][j] = element*cob_matrix

In [40]:
c_matrix[0]

[(11, 14, 6, 2, 3, 6),
 (0, 3, 20, 4, 14, 5),
 (6, 4, 16, 21, 6, 18),
 (1, 3, 18, 13, 4, 0),
 (7, 0, 22, 8, 15, 22),
 (0, 19, 14, 19, 9, 11)]

[5 4 4 6 0]
[4 5 3 2 0]
[4 3 5 2 5]
[6 2 2 5 4]
[0 0 5 4 6]

In [6]:
def getIndices(y,x, k, r): 
    y = int(y)
    x = int(x)
    rk  = r*k
    t1 = x//rk^3
    rem = x% rk^3 
    a1 = rem//rk^2
    rem = rem%rk^2
    t2 = rem//rk
    rem = rem%rk
    a2= rem 
    
    
    d = y//((k^2-k)*(k^2 - k)/4)
    rem = y%((k^2-k)*(k^2 - k)/4)
    l = rem//int(((k^2 - k)/2)) + 1
    rem = rem%((k^2 - k)/2)
    j = rem + 1 
    
   
    lx  = 1
    jx = 1
    ly = 0
    jy = 0
    continuel = True
    continuej = True
    startl = k*(k-1)/2
    startj = k*(k-1)/2
    for i in range(k-1):
        if continuel == True:
            startl -= k-1 - i
            if l> startl:
                lx = k-1 - i 
                ly = l - startl - 1
                continuel = False
        if continuej == True:
            startj -= k-1 - i
            if j> startj:
                jx = k-1 - i 
                jy = j - startj - 1
                continuej = False
    return int(t1), int(a1), int(t2), int(a2), int(d), int(lx), int(ly), int(jx), int(jy)
            
            
        
    
    

In [7]:
print([i for i in range(5)])

[0, 1, 2, 3, 4]


In [37]:
## j = jx, i = jy, r = lx, l = ly

def getSimpleCoeff(y,x,k, r, matrixList):
    t1, a1, t2, a2, d, lx, ly, jx, jy = getIndices(y,x,k,r)
    ##if(lx*k^2 + ly*k > jx * k^2 + jy*k): 
       ## return 0
    if x < r*k:
       
        return matrixList[x][jy][ly]*matrixList[x][jx][lx] - matrixList[x][jy][lx]*matrixList[x][jx][ly]
    else: 
      
        x = (rk+1)*(rk)/2 - x
        ##x = x - rk
        start = r*k*(r*k-1)/2
        x1 = 1
        x2 = 0
        for i in range(r*k-1):
            start -= r*k-1 - i
            if x> start:
                x1 = r*k-1 - i 
                x2 = x - start - 1
                break
       
        return matrixList[x1][jy][ly]*matrixList[x2][jx][lx] - matrixList[x1][jy][lx]*matrixList[x2][jx][ly] + matrixList[x2][jy][ly]*matrixList[x1][jx][lx] - matrixList[x2][jy][lx]*matrixList[x1][jx][ly]
def getMonomialOrder(y,x,k, r, matrixList):
    t1, a1, t2, a2, d, lx, ly, jx, jy = getIndices(y,x,k,r)
    ##if(lx*k^2 + ly*k > jx * k^2 + jy*k): 
       ## return 0
    if x < r*k:
       
        return (x,x)
    else: 
      
        x = (rk+1)*(rk)/2 - x
        ##x = x - rk
        start = r*k*(r*k-1)/2
        x1 = 1
        x2 = 0
        for i in range(r*k-1):
            start -= r*k-1 - i
            if x> start:
                x1 = r*k-1 - i 
                x2 = x - start - 1
                break
       
        return (x1,x2)
            
               
               

In [9]:
def getLinearizedCoeff(y, x, k, r, matrixList, c_matrix):
    if y % 100 == 0 and x == 0: 
        print(y)
    t1,a1,t2,a2,d,lx,ly,jx,jy = getIndices(y,x,k,r)

    if t1*r*k + a1 > t2*r*k + a2: 
      
        return 0
    c = c_matrix[a1][a2][d]
    coeff = c*(matrixList[t1][jy][ly]*matrixList[t2][jx][lx] - matrixList[t1][jy][lx]*matrixList[t2][jx][ly])

    coeff2 = 0
    if t1*r*k + a1 != t2*r*k + a2:
        
        temp = t1
        t1 = t2
        t2 = temp

        temp = a1
        a1 = a2
        a2 = temp
        
        c2 = c_matrix[a1][a2][d]
        coeff2 = c2*(matrixList[t1][jy][ly]*matrixList[t2][jx][lx] - matrixList[t1][jy][lx]*matrixList[t2][jx][ly])
           
    return coeff + coeff2
    

In [131]:
k = 6
r = 3
rk = r*k
matrixList = [0 for i in range(rk)]
for i in range(rk): 
    c = Matrix(basefield, k, lambda i, j:basefield.random_element())
    c2 = c+ c.transpose() 
    matrixList[i] = c2

In [359]:
q = 3
basefield = GF(q)
k = 4
r = 2
rk = r*k
y, F, F_r, c, d = ConstructSidon2k(q, k)
matrixList, sidonbasis, mult_table, F_r_basis , origbasis = publicKey(y,q,F,F_r)
basefield = GF(q)

##Construct a random basis for F_r 
F_r_basis_new = Matrix(basefield, rk, lambda i,j: basefield.random_element())
while F_r_basis_new.is_invertible() == False: 
     F_r_basis_new = Matrix(basefield, rk, lambda i,j: basefield.random_element())
cob_matrix = F_r_basis_new.inverse()
basiselements = []
for i in range(rk): 
    basiselements += [convertFromLong(F_r_basis_new[i], F, F_r)]

[2 1 1 1 0 1 0 2]
[2 2 2 2 2 1 0 1]
[1 2 1 1 1 2 0 1]
[1 2 2 0 1 2 1 1]
[1 1 1 2 1 2 1 0]
[2 1 1 2 2 2 1 1]
[2 1 1 1 0 1 1 2]
[1 2 0 0 1 1 2 1]


In [236]:
F_r_invertible = Matrix(F_r, 15, lambda i, j: F_r.random_element())

In [237]:
while F_r_invertible.is_invertible() == False: 
     F_r_invertible = Matrix(basefield, 2*rk, lambda i,j: F_r_invertible.random_element())

In [238]:
simple_mat = Matrix(basefield, (k*(k-1)/2)^2, (rk+1)*(rk)/2, lambda i, j: getSimpleCoeff(i,j,k,r,matrixList))

In [239]:
basis2 = simple_mat.transpose().kernel().basis()

In [240]:
newbasis2 = F_r_invertible*Matrix(basis2)
newmatlist = [0 for i in range(2*r*k)]
for i in range(2*r*k): 
    newmat = [[0 for j in range(rk)] for l in range(rk)]
    for j in range(len(newbasis2[i])): 
        y,x = getMonomialOrder(0,j,k,r,matrixList)
        
        newmat[y][x] = newbasis2[i][j]
        newmat[x][y] = newbasis2[i][j]
    newmatlist[i] = Matrix(newmat)





























In [360]:

omega_mat = Matrix(F_r, (2*k*(2*k-1)/2)^2, (2*rk+1)*(2*rk)/2, lambda i, j: getSimpleCoeff(i,j,k,r,matrixList))

KeyboardInterrupt: 

In [344]:
omega_mat.rank()

104

In [361]:

omega_mat = Matrix(F_r, (k*(k-1)/2)^2, (rk+1)*(rk)/2, lambda i, j: getSimpleCoeff(i,j,k,r,matrixList))

In [362]:
omega_mat = omega_mat.matrix_from_rows(omega_mat.pivot_rows())

In [363]:
R = PolynomialRing(F_r,'x', 8, order = "degrevlex")
indeterminates = R.gens()
R.inject_variables()
monomial_order = []
for i in range(omega_mat.ncols()): 
    x1, x2 = getMonomialOrder(0,i,k,r,matrixList)
    monomial_order +=[indeterminates[x1]*indeterminates[x2]]

Defining x0, x1, x2, x3, x4, x5, x6, x7


In [364]:
ideal1 = omega_mat*vector(monomial_order).column()

In [365]:
ideal1 = list(ideal1)
for i in range(len(ideal1)):
    ideal1[i] = ideal1[i][0]

In [366]:
ideal1 = ideal(ideal1)
ideal1.degree_of_semi_regularity()

3

In [368]:
a = ideal1.groebner_basis()

In [369]:
a = ideal(a)

In [370]:
a.degree_of_semi_regularity()

3

In [380]:
a2 = a.subs(x0 = 1)

In [381]:
a2 = a2.subs(x2 = 0)
a2.dimension()

verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.
verbose 0 (1083: multi_polynomial_ideal.py, dimension) Warning: falling back to very slow toy implementation.


2

In [308]:
##a2 = a2.subs(x3 = 1)
a2.dimension()

verbose 0 (1083: multi_polynomial_ideal.py, dimension) Warning: falling back to very slow toy implementation.


2

In [382]:
R2 = R.remove_var(x0)

In [383]:
R2.inject_variables()

Defining x1, x2, x3, x4, x5, x6, x7


In [266]:
R2 = R2.remove_var(x1)

In [384]:
R2 = R2.remove_var(x2)

In [385]:
a2 = ideal([R2(i) for i in a2.gens()])

TypeError: not a constant polynomial

In [377]:
ideal(a2).dimension()

verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.
verbose 0 (1083: multi_polynomial_ideal.py, dimension) Warning: falling back to very slow toy implementation.


2

In [269]:
a3 = ideal(a3).groebner_basis()

verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.


In [317]:
Ideal(a3).variety()

verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.
verbose 0 (1083: multi_polynomial_ideal.py, dimension) Warning: falling back to very slow toy implementation.
verbose 0 (2260: multi_polynomial_ideal.py, variety) Warning: falling back to very slow toy implementation.
verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.
verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.
verbose 0 (3722: multi_polynomial_ideal.py, groebner_basis) Warning: falling back to very slow toy implementation.


IndexError: tuple index out of range

In [17]:
##matrixList = matrixList[0:3]


simple_mat = Matrix(basefield, (k*(k-1)/2)^2, (rk+1)*(rk)/2, lambda i, j: getSimpleCoeff(i,j,k,r,matrixList))

In [20]:
simple_mat.rank()

35

In [22]:
basis2 = simple_mat.transpose().kernel().basis()

In [ ]:
simple_mat_basis = (simple_mat.transpose().matrix_from_rows(simple_mat.transpose().pivot_rows()))
kernel1 = simple_mat.kernel().basis()
cob_mat = simple_mat_basis.stack(Matrix(kernel1)).transpose().inverse()

In [240]:
simple_mat.transpose().pivot_rows()

(0, 1, 3)

In [248]:
print(simple_mat.transpose().kernel().basis())

[
(1, 0, 0, 1, 1, 0),
(0, 1, 0, 0, 1, 1),
(0, 0, 1, 1, 0, 1)
]


In [241]:
dependencies = (cob_mat*simple_mat).transpose()

In [242]:
dependencies[4]                           #  #  #  #  #           #  #  #  #  #        #  #  #  #  #

(1, 1, 0, 0, 0, 0, 0, 0, 0)

In [182]:
#14,15,16,17,18
#22,23,24,25,26
#29,30,31,32,33

simple_mat.rank()

## 94 - 90, 84-80, 74-70 form a space for 64 - 50

3

In [207]:
y

(6*z^2 + 5*z + 3)*a

In [105]:
getSimpleCoeff(0,44,k,r,matrixList)

5 0


1

In [236]:
eqn_mat = Matrix(basefield, (k^3*(k-1)^2)/2, rk^4, lambda i,j: getLinearizedCoeff(i,j, k, r, matrixList, c_matrix))

0


In [211]:
getSimpleCoeff(0,3,k,r,matrixList)

2 1


0

In [72]:
simple_mat[11]

(4, 6, 4, 3, 5, 6, 3, 2, 2, 3, 4, 4, 2, 3, 0, 5, 1, 5, 2, 6, 5, 6, 1, 4, 6, 1, 3, 0, 0, 1, 2, 0, 6, 4, 6, 4, 4, 3, 2, 0, 1, 6, 4, 3, 0, 0, 1, 5, 4, 3, 6, 6, 0, 3, 5)

In [214]:
simple_mat.rank()

35

In [18]:
print(simple_mat.nrows(), simple_mat.ncols())

100 120


In [ ]:
eqn_mat[1]

In [23]:
eqn_mat.nrows()

6174

In [24]:
eqn_mat.rank()

1078

In [165]:
kernel = simple_mat.transpose().kernel()

In [166]:
basis = kernel.basis()

In [167]:
null_mat = Matrix(basis)

In [151]:
null_mat.rank()

3

In [168]:
independent_equations = simple_mat.matrix_from_rows(simple_mat.pivot_rows())

In [169]:
independent_equations.nrows()

3

In [170]:
cob = independent_equations.stack(null_mat)

In [129]:
b = cob.kernel().basis()

In [130]:
cob = cob.matrix_from_rows(cob.pivot_rows())

In [34]:
cob.nrows()

9998

In [36]:
b = Matrix(b)
cob = cob.stack(b)

In [171]:
cob = cob.inverse()
rep = simple_mat*cob

In [172]:
simple_mat.pivot_rows()

(0, 1, 2)

In [178]:
rep[8]

(4, 1, 3, 0, 0, 0)

In [17]:
getIndices(0, 85, k, r)

(0, 0, 5, 10, 0, 1, 0, 1, 0)

In [56]:
t1,a1,t2,a2,d,lx,ly,jx,jy = getIndices(1,6,k,r)
c = c_matrix[a1][a2][d]
matrixList[t1][jy][lx]*matrixList[t2][jx][ly]


0

In [183]:
getIndices(matrixList[t1][jy][ly]*matrixList[t2][jx][lx] - matrixList[t1][jy][lx]*matrixList[t2][jx][ly],1, k, r)

NameError: name 't1' is not defined

In [14]:
getSimpleCoeff(1,85,k,r,matrixList, c_matrix)

NameError: name 'c_matrix' is not defined

In [73]:
[eqn_mat[i][4] for i in range(54)]

[22,
 22,
 7,
 22,
 7,
 10,
 7,
 7,
 10,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 10,
 10,
 22,
 10,
 22,
 15,
 22,
 22,
 15,
 12,
 12,
 8,
 12,
 8,
 18,
 8,
 8,
 18,
 11,
 11,
 15,
 11,
 15,
 5,
 15,
 15,
 5,
 10,
 10,
 22,
 10,
 22,
 15,
 22,
 22,
 15]

In [66]:
1//3

0

In [114]:
for x in range(16*81): 
    x1,x2,x3,x4,d,lx,ly,jx,jy = getIndices(x,0,3,r)
    print(lx,ly,jx,jy)

1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0


2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0
2 0 2 0
2 0 2 1
2 1 1 0
2 1 2 0
2 1 2 1
1 0 1 0
1 0 2 0
1 0 2 1
2 0 1 0


In [146]:
Matrix(matrixList[2]).rank()

4

In [1]:
c_matrix[0]

NameError: name 'c_matrix' is not defined

In [34]:
sidonbasis

[z^4 + 4*z^3 + z^2 + z + 1,
 z^4 + 6*z^3 + z^2 + 5*z + 6,
 2*z^4 + 4*z^3 + 3*z^2 + 4*z + 6,
 5*z^4 + 5*z^3 + 2*z^2 + z + 4,
 5*z^4 + 5*z^3 + 5*z^2 + 5*z + 3]

In [172]:
2^3*2

16

In [247]:
zeroVector = vector([0 for i in range((k^3*(k-1)^2)/2)])
ans = 1
while ans!=zeroVector.column():
    randomVec = vector([basefield.random_element() for i in range(rk^2) ])
    testMatrix = randomVec.column()*randomVec.row()
    testVecList = []
    for i in range(rk^2): 
        testVecList += list(testMatrix[i])
    testVec = vector(testVecList)
    ans = eqn_mat*testVec.column()
    

KeyboardInterrupt: 

(0, 0, 0, 0, 0, 0)

In [38]:
vector(sidonbasis[0])

(z^4 + 4*z^3 + z^2 + z + 1, 0)

In [13]:
list(vector(F.random_element()))

[4, 1, 3, 5, 1]

In [102]:
matrixList[10]

[6 0 1 5 2]
[0 3 2 6 3]
[1 2 2 3 6]
[5 6 3 2 5]
[2 3 6 5 3]

In [103]:
matrixList[4]

[6 0 1 5 2]
[0 3 2 6 3]
[1 2 2 3 6]
[5 6 3 2 5]
[2 3 6 5 3]

'[1, 2]'

In [5]:
# implementation of Arri's algorithm to compute a Groebner basis
# "The F5 Criterion revised"
# paper submitted to JSC in 2009, accepted conditionally in 2010 subject to revision,
# resubmitted 2010
# http://arxiv.org/abs/1012.3664

# usage: f5_arri(F) where F is a list of polynomials
# result: groebner basis of F, with signatures
# example:
#   sage: R = PolynomialRing(GF(32003),x,5)
#   sage: I = sage.rings.ideal.Cyclic(R,5).homogenize()
#   sage: F = list(I.gens())
#   sage: B = f5_arri(F)
#   >> There were 0 reductions to zero.
#   sage: len(B)
#   >> 166
#   sage: F.reverse()
#   sage: B = f5_arri(F)
#   >> There were 0 reductions to zero.
#   sage: len(B)
#   >> 39
# as with all incremental algorithms, efficiency depends on the ordering of F

verbose_zero_reduction = 0

verbose_generation = 1
verbose_reduction = 1

verbose_rejection = 1

# polysort
# used to sort polynomials by increasing signature
# inputs: (f,S(f)) and (g,S(g)), labeled polynomials
# outputs: 1 if (f,S(f)) > (g,S(g))
#        -1 if (f,S(f)) < (g,S(g))
#         0 if (f,S(f)) = (g,S(g))
def polysort(f,g):
  fp,Sf = f
  gp,Sg = g
  sigord = sigsort(Sf,Sg)
  if sigord != 0:
    return sigord
  else:
    if fp.lm() > gp.lm():
      return 1
    else:
      return -1
  return 0

# sigsort
# used to sort signatures
# inputs: S(f) and S(g), labeled polynomials
# outputs: 1 if S(f) > S(g)
#        -1 if S(f) < S(g)
#         0 if S(f) = S(g)
def sigsort(s1,s2):
  t1,i1 = s1
  t2,i2 = s2
  if i1 < i2:
    return 1
  if i1 > i2:
    return -1
  if t1 > t2:
    return 1
  if t1 < t2:
    return -1
  return 0

# is_primitive
# tests whether a polynomial is primitive
# inputs: polynomial f, S(f), basis G
# outputs: whether uf*f is primitive
def is_primitive(f, Sf, G):
  R = f.parent()
  for (h,Sh) in G:
    if h != f and Sh[1] == Sf[1] and R.monomial_divides(Sh[0],Sf[0]):
      t = R.monomial_quotient(Sf[0],Sh[0])
      if t*h.lm() == f.lm():
        return False
  return True

# prune_rewritables
# removes rewritable elements from B
# this is NOT the same as Faugere's rewritable algorithm;
# see the paper for details
# inputs: polynomial ring R, wokring basis G, S-polynomials B
# outputs: (probably) smaller B
def prune_rewritables(R,G,B):
  Bnew = set()
  for (f,Sf) in B:
    rewritable = False
    t = f.lm()
    for (g,Sg) in B:
      if Sg[1] == Sf[1] and R.monomial_divides(Sg[0],Sf[0]):
        u = R.monomial_quotient(Sf[0],Sg[0])
        if u*g.lm() < t:
          rewritable = True
          continue
    if not rewritable:
      for (g,Sg) in G:
        if Sg[1] == Sf[1] and R.monomial_divides(Sg[0],Sf[0]):
          u = R.monomial_quotient(Sf[0],Sg[0])
          if u*g.lm() < t:
            rewritable = True
            continue
      if not rewritable:
        Bnew.add((f,Sf))
  return Bnew

# is_normal
# completes test whether a critical pair is a normal pair in Arri's definition
# (beyond inequality of signature)
# inputs: polynomials f and g, S(f), S(g) monomials uf and ug, basis G
# outputs: whether (f,g) is a normal pair
def is_normal(f, Sf, uf, G, B):
  R = f.parent()
  # Faugere's normal?
  if not any(Sh[1]>Sf[1] and R.monomial_divides(h.lm(),uf*Sf[0]) for (h,Sh) in G):
    # primitive?
    return is_primitive(f,Sf,G) and is_primitive(f,Sf,B)
    #return True
  # not even Faugere's normal, let alone primitive
  return False

# Sreduce
# inputs: polynomial f, S(f), basis G, rewritings RW
# outputs: S-irreducible form of f
def Sreduce(f,Sf,G,B):
  R = f.parent()
  reduced = True
  while reduced:
    reduced = False
    for (g,Sg) in G:
      if R.monomial_divides(g.lm(),f.lm()):
        t = R.monomial_quotient(f.lm(),g.lm())
        if sigsort(Sf,(t*Sg[0],Sg[1])) == 1:
          if is_normal(g, Sg, t, G, B) and is_primitive(g, Sg, G) and is_primitive(g, Sg, B):
            reduced = True
            f -= t*g
            if f == 0:
              return f
            f *= f.lc()**(-1)
          else:
            verbose("reduction of "+str(Sf)+" by "+str(Sg)+" rejected: not normal",level=verbose_rejection)
        else:
          verbose("reduction of "+str(Sf)+" by "+str(Sg)+" rejected: too large",level=verbose_rejection)
  return f

# UpdatePairs
# inputs: basis G, known new polynomials B, polynomial f, S(f)
# outputs: new S-polynomials
def UpdatePairs(G,B,f,Sf):
  Bnew = set()
  if is_primitive(f,Sf,G) and is_primitive(f,Sf,B):
    R = f.parent()
    for (g,Sg) in G:
      tf = f.lm()
      tg = g.lm()
      t = tf.lcm(tg)
      uf = R.monomial_quotient(t,tf)
      ug = R.monomial_quotient(t,tg)
      # normal pair?
      siguf = (uf*Sf[0],Sf[1])
      sigug = (ug*Sg[0],Sg[1])
      if siguf != sigug:
        if is_normal(f,Sf,uf,G,B) and is_normal(g,Sg,ug,G,B):
          if sigsort(siguf,sigug) == 1:
            sig = siguf
          else:
            sig = sigug
          verbose("generating "+str(sig)+" from "+str(Sf)+" and "+str(Sg),level=verbose_generation)
          S = uf*f - ug*g
          S *= S.lc()**(-1)
          Bnew.add((S,sig))
        else:
          verbose("pair "+str(Sf)+", "+str(Sg)+" rejected: not normal",level=verbose_rejection)
      else:
        verbose("pair "+str(Sf)+", "+str(Sg)+" rejected: equal signature",level=verbose_rejection)
  return Bnew
  
# prune_not_normal
# prunes polynomials of signature that are not normal
# inputs list of polynomials B, list of polynomials G
# outputs: pruned version of B
def prune_not_normal(B,G):
  Bnew = set()
  while len(B) != 0:
    f,Sf = B.pop()
    if is_normal(f,Sf,Integer(1),G,Bnew.union(B)):
      Bnew.add((f,Sf))
  return list(Bnew)

# f5_arri
# compute groebner basis
# inputs: list of polynomials F
# outputs: groebner basis (we hope) of ideal of F
def f5_arri(F):
  L = set()
  G = set()
  R = F[0].parent()
  B = [(F[i]*F[i].lc()**(-1),(R(1),i)) for i in range(len(F))]
  while len(B) != 0:
    Bnew = set()
    for (f,Sf) in B:
      if not any(Sg[1]==Sf[1] and R.monomial_divides(Sg[0],Sf[0]) for Sg in L):
        Bnew.add((f,Sf))
    B = Bnew
    #i = len(B)
    B = prune_rewritables(R,G,B)
    #if len(B) < i:
    #  print "pruned", i - len(B)
    B = prune_not_normal(B,G)
    B.sort(key = polysort)
    f,Sf = B.pop(0)
    while len(B) != 0 and B[0][1] == Sf:
      B.pop(0)
    f = Sreduce(f,Sf,G,B)
    verbose("reduced "+str(Sf)+" to "+str(f.lm()),level=verbose_reduction)
    if f != 0:
      if is_primitive(f,Sf,G) and is_primitive(f,Sf,B):
        B.extend(UpdatePairs(G,B,f,Sf))
      G.add((f,Sf))
    else:
      L.add(Sf)
      verbose("zero reduction: "+str(Sf),level=verbose_zero_reduction)
  print("There were", len(L), "reductions to zero.")
  return G


In [1]:
load('minrankminor.sage')

ModuleNotFoundError: No module named 'fgb_sage'

In [2]:

def minorAttack(q,k):
    r = 2
    basefield = GF(q)
    rk = r*k
    y, F, F_r, d, c = ConstructSidon2k(q, k)
    matrixList, sidonbasis, mult_table, F_r_basis , origbasis = publicKey(y,q,F,F_r)
    basefield = GF(q)

    ##Construct a new random basis for F_r 
    F_r_basis_new = Matrix(basefield, rk, lambda i,j: basefield.random_element())
    while F_r_basis_new.is_invertible() == False: 
         F_r_basis_new = Matrix(basefield, rk, lambda i,j: basefield.random_element())
    cob_matrix = F_r_basis_new.inverse()
    basiselements = []
    ##represent the multiplication table of the new basis over that basis
    for i in range(rk): 
        basiselements += [convertFromLong(F_r_basis_new[i], F, F_r)]
    c_matrix = [[0 for i in range(rk)] for j in range(rk)]
    new_mult_table = [[i*j for i in basiselements] for j in basiselements]
    for i in range(rk): 
        for j in range(rk): 
            element = convertToLong(new_mult_table[i][j])
            c_matrix[i][j] = element*cob_matrix
    ##Construct the coefficient matrix for the system. Not efficient but works for small k 
    eqn_mat = Matrix(basefield, (k^3*(k-1)^2)/2, rk^4, lambda i,j: getLinearizedCoeff(i,j, k, r, matrixList, c_matrix))
    R = PolynomialRing(GF(q),'x', 4*k*k, order = "degrevlex")
    indeterminates = R.gens()
    R.inject_variables()
    pivot_cols = eqn_mat.transpose().pivot_rows()
    eqn_mat = eqn_mat.matrix_from_rows(eqn_mat.pivot_rows())
    indices = []
    for i in range(eqn_mat.ncols()):
        if eqn_mat.transpose()[i] == zero_vector(eqn_mat.nrows()):
            continue
        indices += [i]
    eqn_mat = eqn_mat.transpose().matrix_from_rows(indices).transpose()
    monomial_order = []
    for i in indices:
        t1,a1,t2,a2,d,lx,ly,jx,jy =  getIndices(0,i,k,r)
        monomial_order += [indeterminates[t1*r*k + a1]*indeterminates[t2*r*k + a2]]
    ideallist = list(eqn_mat*vector(monomial_order).column())
    ideallist = [R(i) for i in ideallist]
    I = ideal(ideallist)
    return I

In [14]:
I = minorAttack(3,2)

[0 1 2 1]
[0 0 2 0]
[0 0 2 1]
[1 1 0 0]
Defining x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15


In [120]:
I2 = I.subs(x1 = 0, x2 = 0, x4 = 1, x5 = 0, x6 = 0, x7 = 2,x8 = 2,x9 = 0, x10 = 0, x12 = 1, x13 = 0, x14 = 0)

In [122]:
R2 = PolynomialRing(GF(3), 'x11,x15')

In [81]:
I2

Ideal (-x7^2 + x7*x11 + x7*x15 + x15^2 + x8 + 1, -x7^2 - x7*x8 + x7*x11 + x7*x15 + x15^2 + x7 + x8 - x11 + 1, x7*x8 - x7 + x11, x7^2 - x7*x11 - x7*x15 - x15^2 + x8 + 1) of Multivariate Polynomial Ring in x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15 over Finite Field of size 3

In [123]:
I2.dimension()

14

In [124]:
system2 = [R2(x) for x in I2.gens()]

In [125]:
I3 = ideal(system2)

In [126]:
I3.dimension()

0

In [118]:
I3 = I3.subs(x7 = 2)

In [106]:
I3

Ideal (-x7^2 + x7*x11 + x7*x15 + x15^2, -x7^2 + x7*x11 + x7*x15 + x15^2 - x7 - x11, x7 + x11, x7^2 - x7*x11 - x7*x15 - x15^2) of Multivariate Polynomial Ring in x7, x8, x11, x15 over Finite Field of size 3

In [92]:
I3.varieties()

AttributeError: 'MPolynomialIdeal' object has no attribute 'varieties'

In [127]:
I3.variety()

[{x15: 2, x11: 1}]